// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjh5Yp2XkXDdrKDb1CWSbfdhf_0efRd5U',
    appId: '1:852214227083:web:628ac89deacf464354748e',
    messagingSenderId: '852214227083',
    projectId: 'chat-app-8e0fd',
    authDomain: 'chat-app-8e0fd.firebaseapp.com',
    storageBucket: 'chat-app-8e0fd.appspot.com',
    measurementId: 'G-QX0NKDE86P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2FrHTaxTsihjo-n_d-ItypGYUseLdixE',
    appId: '1:852214227083:android:9dbcf31053e80f8e54748e',
    messagingSenderId: '852214227083',
    projectId: 'chat-app-8e0fd',
    storageBucket: 'chat-app-8e0fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC45GAgJfUlsyav49a_zXUWpX5X_elpo9M',
    appId: '1:852214227083:ios:d153a8edd596dd4354748e',
    messagingSenderId: '852214227083',
    projectId: 'chat-app-8e0fd',
    storageBucket: 'chat-app-8e0fd.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC45GAgJfUlsyav49a_zXUWpX5X_elpo9M',
    appId: '1:852214227083:ios:ec6ca06764df8ca454748e',
    messagingSenderId: '852214227083',
    projectId: 'chat-app-8e0fd',
    storageBucket: 'chat-app-8e0fd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjh5Yp2XkXDdrKDb1CWSbfdhf_0efRd5U',
    appId: '1:852214227083:web:8237c1b424ae81f054748e',
    messagingSenderId: '852214227083',
    projectId: 'chat-app-8e0fd',
    authDomain: 'chat-app-8e0fd.firebaseapp.com',
    storageBucket: 'chat-app-8e0fd.appspot.com',
    measurementId: 'G-2GQCC5902B',
  );
}
